version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli@16.0.6
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --prod
artifacts:
  base-directory: dist/my-angular-project
  files:
    - '**/*'